### ISSUE TITLE
openscad support

### ISSUE THREAD

**Issue by sugizo** [CodeToCAD/CodeToCAD#227]
any plan to support openscad ?

**ref**
https://openscad.org

best regards

**Comment by shehabattia96** [comment]
Not in the short term, for several reasons:
- OpenSCAD uses [CGAL](https://www.cgal.org/) under the hood, and its models are mesh based, same as Blender. We already have decent Blender implementation, and thus additional support for mesh-geometry based software is not high on my list.
- Supporting OpenSCAD would just be wrapping their calls, we would just be another [SolidPython](https://solidpython.readthedocs.io/en/latest/)
- OpenSCAD does not have [a scripting API](https://github.com/openscad/openscad/issues/1825). An integration would have to write a .scad file to disk and then call the OpenSCAD binary via CLI. It's doable, but a bit inconvenient.


Thank you for expressing interest in supporting OpenSCAD, you're the first to do so. I'll add it to our list because it's an easy integration, but I wouldn't be able to get to it until I get more help. ;)

fyi, the next planned integrations at this time are: 
- Onshape OR [Replicad](https://replicad.xyz/), for BREP software support, as well as the ability to support STEP files.
- KiCAD for electronic-CAD software support.
- PyBullet for simulation library support.

**Comment by shehabattia96** [comment]
Thank you very much for reaching out @sugizo! Feel free to reopen if you have any questions or comments.

Please star/watch and join our [Discord server](https://discord.gg/UkFQsgZQPf) for updates! :)
